name: Validate Flyway Migration Check
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: number
jobs:
  build:
    name: Validate Flyway Migration Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log('${{ inputs.target }}')
            
            const check_id = ${{ inputs.target }}
            
            const check = await github.rest.checks.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  check_run_id: check_id
                });
                        
            console.log(check)
            
            return check
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.check_run.pull_requests[0].base.ref }}
          fetch-depth: 1
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.check_run.pull_requests[0].number }}/merge
          fetch-depth: 1
      - name: Export new migrates
        id: export-new-migrates
        run: |
          git diff --name-only --diff-filter=A origin/${{ github.event.check_run.pull_requests[0].base.ref }} HEAD | grep -E 'java/db/' > new_migrates.txt || true
          echo "Exported migrates"
      - name: Check migrates empty
        id: check-migrates-empty
        run: |
          if [ ! -s new_migrates.txt ]; then
            echo "skip-steps=true" >> $GITHUB_ENV
            echo "Flyway validation results:" >> $GITHUB_STEP_SUMMARY
            echo "No new migrates, skipping validation" >> $GITHUB_STEP_SUMMARY
            echo "No migrates skipping all following steps"
          else
            echo "skip-steps=false" >> $GITHUB_ENV
            echo "Found new migrates, continue with validation"
          fi
      - name: Parse pom.xml version
        if: env.skip-steps != 'true'
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Set up Java
        if: env.skip-steps != 'true'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Java Validation
        if: env.skip-steps != 'true'
        run: java .github/java/FlywayValidation.java ${{ env.version }} new_migrates.txt
      - name: Update check run status
        uses: actions/github-script@v6
        with:
          script: |
            await github.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: ${{ inputs.target }},
              conclusion: 'success', // or 'failure' or 'neutral'
              output: {
                title: 'Check completed',
                summary: 'All checks passed.'
              }
            });
