name: Validate Flyway
on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  call_workflow_PR:
    name: PR Workflow Call
    needs: main_PR_job
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.main_PR_job.outputs.matrix)}}
    uses: ./.github/workflows/validation_workflow_call.yml
    with:
      target: ${{ matrix.check_id }}

  main_PR_job:
    name: PR Job
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-pr-check.outputs.result }}
    steps:
      - name: Create check for PR
        id: create-pr-check
        uses: actions/github-script@v6
        with:
          script: |
            // create/overwrite existing check
            const response = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Flyway Validation PR Check',
              head_sha: context.payload.pull_request.head.sha,
              status: 'in_progress',
              started_at: new Date().toISOString()
            });
            
            const identifier = response.data.id + ":" + context.payload.pull_request.number + ":" + context.payload.pull_request.base.ref;
            const json = { "check_id": [ identifier ] };
            console.log(json);
            return json;
