name: Validate Flyway Migration
on:
  pull_request:
    types: [ opened, synchronize, edited ]
  push:
    branches:
      - master
jobs:
  validate_on_pull_request:
    name: Validate Flyway Job PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_ignored'
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 1
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Export new migrates
        id: export-new-migrates
        run: |
          git diff --name-only --diff-filter=A origin/${{ github.base_ref }} HEAD | grep -E 'java/db/' > new_migrates.txt || true
          echo "Exported migrates"
      - name: Check migrates empty
        id: check-migrates-empty
        run: |
          if [ ! -s new_migrates.txt ]; then
            echo "skip-steps=true" >> $GITHUB_ENV
            echo "Flyway validation results:" >> $GITHUB_STEP_SUMMARY
            echo "No new migrates, skipping validation" >> $GITHUB_STEP_SUMMARY
            echo "No migrates skipping all following steps"
          else
            echo "skip-steps=false" >> $GITHUB_ENV
            echo "Found new migrates, continue with validation"
          fi
      - name: Parse pom.xml version
        if: env.skip-steps != 'true'
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Set up Java
        if: env.skip-steps != 'true'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Java Validation
        if: env.skip-steps != 'true'
        run: java .github/java/FlywayValidation.java ${{ env.version }} new_migrates.txt

  validate_on_pull_request_create:
    name: Validate Flyway Job PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Create check
        id: create-check
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Flyway Validation1',
              head_sha: context.payload.pull_request.head.sha,
              status: 'in_progress',
              started_at: new Date().toISOString()
            });
            console.log(response);
            const json = { "run_id": response.data.id };
            console.log(json);
            console.log(fromJSON(response.data.id));
            return response.data.id;
      - name: Bla
        run: |
          echo "run_matrix={\"run_id\": [${{ steps.create-check.outputs.result }}]" >> $GITHUB_ENV
          echo "${{ env.run_matrix }}"
    # needs: call_workflow

  validate_on_push_to_master:
    name: Validate Flyway Job PUSH
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: List PRs
        id: prs
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
            // get PRs targeting pushed branch
            const PRs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: context.ref,
              state: 'open'
            });
            console.log(`Found ${PRs.data.length} open PRs targeting ${ context.ref }.`);
            const SHAs = PRs.data.map(pr => pr.head.sha);
            for (const sha of SHAs) {
              console.log(`SHA: ${sha}`);
              console.log(`Context SHA: ${context.sha}`);
            
              if (sha == context.sha) {
                console.log(`SHA ${sha} is the same as the one that triggered the workflow, skipping...`);
                continue;
              }
            
              const response = await github.rest.checks.listForRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: sha
              });
            
              if (response.data.total_count == 0) {
                console.log(`No checks found for ${sha}, skipping...`);
                continue;
              }
            
              const checks = response.data.check_runs;
              console.log(`Found ${checks.length} checks.`);
              const checkIDs = response.data.check_runs.map(check => check.id);
              console.log('Check IDs: ' + checkIDs.join(', '));
            
              for (const check of checkIDs) {
                const check_bla = await github.rest.checks.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  check_run_id: check
                });
            
                console.log(`Check ${check} name: ${check_bla.data.name}`);
                if (!check_bla.data.name.toLowerCase().includes('Validation1')) {
                  console.log(`Check ${check} is not a Flyway check, skipping...`);
                  continue;
                }
            
                for (const pr of check_bla.data.pull_requests) {
                  console.log(`PR: ${pr.number}`);
            
                  await github.rest.pulls.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number,
                    body: 'This PR is outdated, please rebase it on the latest master.'
                  });
                }
            
                console.log(`Updating check ${check}...`);
                
                rerequest_response = await github.rest.checks.rerequestRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  check_run_id: check
                });
            
                console.log(rerequest_response);
                
                // const update_response = await github.rest.checks.update({
                //   owner: context.repo.owner,
                //   repo: context.repo.repo,
                //   check_run_id: check,
                //   name: 'Flyway Validation',
                //   status: 'completed', // set status to 'completed' for example, you can change it as needed
                //   conclusion: 'success', // set conclusion to 'success' for example, you can change it as needed
                //   output: {
                //       title: 'check_name',
                //       summary: 'output',
                //       text: 'text'
                //     }
                // });
                // console.log(update_response);
            
              }
            
            }
